### ISSUE TITLE
1st issue

### ISSUE THREAD

**Issue by troll-hebus** [399man/freedocs#1]
Salut 399man !

Dans ton readme, tu peux ajouter l'adresse officielle qui est toujours valable, à savoir http://www.ll-dd.ch. Il y a une redirection DNS vers logicielsdurables.wordpress.com, parce que le version gratuite de wordpress.com n’autorise pas les noms externes.

Note : je n'ai pas encore géré de projet avec Git, donc je découvre. Merci pour l'invitation !

a+

Troll-hebus

**Comment by 399man** [comment]
OK, noté et corrigé.
Merci.
