### ISSUE TITLE
Vérifications

### ISSUE THREAD

**Issue by troll-hebus** [399man/freedocs#2]
Salut Man!

J'ai clôné ton dépôt en local pour pouvoir faire des modifications sur les affiches. J'ai donc créé une nouvelle branche pour ces modifications. Je l'ai appelée fix.troll-review. 

**Note** : je ne suis pas très familiarisé avec le fonctionnement de git, donc si je procède à des changements qui ne sont pas dans la ligne de ce qui devrait être fait, dis-le moi. 

J'ai commencé à revoir l'affiche "Logiciels libres - quelques références" en vérifiant si les infos étaient toujours à jour. Pour ce qui est de GeLibreEdu et le plan directeur, voici ce que j'ai trouvé sur un doc de 2014 : 

> Etat des lieux
> A la fin de l'année civile 2013, l'ensemble des postes à usage pédagogique de l'enseignement
> primaire est passé à un système libre sous Linux/Ubuntu. Cette migration d'importance s'est déroulée sans difficulté majeure. L'accompagnement au changement réalisé dans les écoles a permis de mettre à jour les compétences MITIC des enseignants et d'augmenter l'utilisation pédagogique des ordinateurs.
> 
> Au secondaire, quelques expériences pilotes ont été réalisées dans le même temps. Avant de poursuivre la migration, le département procédera à une analyse détaillée des coûts et bénéfices   de   chacune   des   options,   ainsi   que   des   incidences   sur   l’usage   des   utilisateurs   pour
> l’enseignement et l’apprentissage

Donc, l'affiche a l'air d'être à jour.

Je poursuis.

a+

Troll-hebus

**Comment by 399man** [comment]
Ok, merci.
