### ISSUE TITLE
Autorisations ?

### ISSUE THREAD

**Issue by troll-hebus** [399man/freedocs#3]
Salut Man,

Quand j'essaie de pousser mes changements, j'obtiens ce message d'erreur : 

> git push origin fix.troll-review 
> Username for 'https://github.com': troll-hebus
> Password for 'https://troll-hebus@github.com': 
> remote: Permission to 399man/freedocs.git denied to troll-hebus.
> fatal: unable to access 'https://github.com/399man/freedocs.git/': The requested URL returned error: 403

<link>https://help.github.com/articles/error-permission-to-user-repo-denied-to-other-user/</link>

Faut-il que tu m'ajoutes (troll-hebus) dans les user autorisés pour écrire dans ton dépôt ?

Merci d'avance !

a+

Troll-hebus

**Comment by 399man** [comment]
Modifié.
Ça devrait être OK.
